apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache-exporter
  name: apache-exporterv1
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-exporter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache-exporter
    spec:
      containers:
      - image: tsarlewey/caapacheimage:1
        name: cloudacademy-apache-server
        ports:
          - containerPort: 80
        resources:
         limits:
          memory: "128Mi"
          cpu: "250m"
      - image: lusotycoon/apache-exporter
        name: apache-exporter
        ports:
          - containerPort: 9117
        resources:
         limits:
          memory: "128Mi"
          cpu: "250m"
      - image: prom/prometheus
        name: prom-server
        ports:
          - containerPort: 9090
        resources:
         limits:
          memory: "128Mi"
          cpu: "250m"
status: {}
