apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: prometheus
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: prometheus
spec:
  type: NodePort
  ports:
  - name: apache-np
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-exporter-svc
  namespace: prometheus
spec:
  ports:
  - name: exporter-ci
    port: 9117
    protocol: TCP
    targetPort: 9117
  selector:
    app: apache-exporter
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: prometheus
spec:
  ports:
  - name: prometheus-np
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: apache-exporter
  type: NodePort

