apiVersion: v1
kind: Service
metadata:
  name: prom-service
spec:
  ports:
  - name: exporter
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: apache-exporter
  type: NodePort