apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-exporter-svc
spec:
  ports:
  - name: exporter
    port: 9117
    protocol: TCP
    targetPort: 9117
  selector:
    app: apache-exporter
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prom-service
spec:
  ports:
  - name: exporter
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: apache-exporter
  type: NodePort